version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    networks:
      - springnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # Puerto para la comunicación con aplicaciones
      - "15672:15672"  # Puerto para acceder a la interfaz de administración de RabbitMQ
    networks:
      - springnet

  redis:
    image: redis:latest
    container_name: redis-srvr
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"  # Puerto para la comunicación con aplicaciones
    networks:
      - springnet

  springboot-app-1:
    image: edflamenco/transaction-svc:v1
    build: .
    container_name: transaction-svc
    ports:
      - "8090:8090"
    networks:
      - springnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres12:5432/bank
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis-srvr
    depends_on:
      - postgres
      - rabbitmq
      - redis

  springboot-app-2:
    image: edflamenco/payment-svc:v1
    build: .
    container_name: payment-svc
    ports:
      - "8080:8080"
    networks:
      - springnet
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis-srvr
    depends_on:
      - springboot-app-1

networks:
  springnet:
    driver: bridge
